### ISSUE TITLE
Cannot install in Xamarin.iOS :(

### ISSUE THREAD

**Issue by knocte** [ricardoalcantara/raven-csharp-light#11]
I get this error:

```
Could not install package 'SharpRavenLight 1.0.0-beta4'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by ricardoalcantara** [comment]
I may have forgotten to publish the latest changed at Nuget.org, Later today I will do that, and we will see if it fix that problem.

**Comment by knocte** [comment]
I think you're right, because the last published version in Nuget targets v1.5 of .NETStandard, while the last commit in this repo contains an upgrade to .NET Standard 2.0.

I'll test the new version as soon as you publish it (please mantain v.4.5.1 compatibility, thanks).

**Comment by ricardoalcantara** [comment]
I tried to build the app, but it's broken and VS 2017 last update does't seams to recognize the csproj, I couldn't take a long look today but I will check that for sure, maybe I will recreate the csproj from scratch, I will consider your need for .net 4.5.1

**Comment by knocte** [comment]
> I tried to build the app, but it's broken and VS 2017 last update

You're right. I'm blown away at how they can break backwards compatibility. I thought MS was the best example of a company keeping backwards compatibility at all costs...

> maybe I will recreate the csproj from scratch, I will consider your need for .net 4.5.1

Actually I need any .NET4.x that is lower than 4.6.1. So I tried to load the solution with VS4Mac today and in fact it works there if I switch the build from 4.5/4.5.1 to 4.6. Maybe this is enough for you to be able to publish a new version to nuget? And then after that I could test it from my side, and then you could try to fix the projects in VS for Windows for v.Next? How does that sound?

**Comment by knocte** [comment]
> in fact it works there if I switch the build from 4.5/4.5.1 to 4.6

I proposed this as a PR in case you didn't see it yet: https://github.com/ricardoalcantara/raven-csharp-light/pull/12

**Comment by ricardoalcantara** [comment]
Actually I didn't. I am going to check that.

**Comment by ricardoalcantara** [comment]
I published a new package on nuger.org
https://www.nuget.org/packages/SharpRavenLight/1.0.0-beta5

Sorry that it took that long, but it's close to xmas and I was a little busy.

**Comment by ricardoalcantara** [comment]
@knocte I forgot to tag you.

**Comment by knocte** [comment]
No worries! Hope you're having happy holidays. Your new version in nuget seems to work (at least at compile time). I'll test sending a sentry event (run time) and if it works, I'll close this. Thanks again.

**Comment by knocte** [comment]
I verified that with 1.0.0 beta5 I can use SharpRavenLight in Xamarin.iOS so I'm closing this (sidetone: however in Android I've found another problem which I have just filed as a separate issue).

**Comment by knocte** [comment]
@ricardoalcantara I'm now facing problems because of the switch from 4.5.x to 4.6 :-(

Do you mind reverting my commit https://github.com/ricardoalcantara/raven-csharp-light/commit/1ee3b5635c9ee9aa7c2421803bdbb9c7dab74415 and publishing a new nuget package to see if it fixes my building issues? (I only submitted that PR of mine as a quick stopgap to let me build in VS4Mac if it was going to take you a while to fix the project files... but given you acted very quickly in the end, my PR was not really needed.)

**Comment by knocte** [comment]
happy new year BTW!

**Comment by ricardoalcantara** [comment]
@knocte I will check that.

**Comment by knocte** [comment]
Actually I think I'm fine with not reverting https://github.com/ricardoalcantara/raven-csharp-light/commit/1ee3b5635c9ee9aa7c2421803bdbb9c7dab74415 for now. Seems to work. I don't remember the last problem I was having.
